### ISSUE TITLE
Mastery Breakdown

### ISSUE THREAD

**Issue by ghost** [jspegele/warframe-mastery-checklist#2]
Hey, not sure if this is used also for suggestions but it would be extremely nice if we could see a breakdown of mastery points per section like on the Warframe profile. I am missing about 40,000 for some reason and I am not sure which section it could be from. I have attached an image as an example of what I mean.

![cuJ5x6](https://user-images.githubusercontent.com/57202889/192824280-65946c53-7181-4521-aaa6-ce28207d3bf0.png)

**Comment by jspegele** [comment]
Thank you for the suggestion. This is something I should be able to add fairly easily as I already have this data separated out, just not being displayed. I need to do some testing to make sure everything matches up to the in-game breakdown and then can add this.

**Comment by ghost** [comment]
> Thank you for the suggestion. This is something I should be able to add fairly easily as I already have this data separated out, just not being displayed. I need to do some testing to make sure everything matches up to the in-game breakdown and then can add this.

Wonderful news! That would be so helpful and make your tool by far the best available.

My only other suggestion (I can make another post), would be a way to toggle the profile sort to be 1:1 with the way Warframe profiles do it. For instance, they break companion up into multiple tabs. A "Warframe Profile Sort" toggle would be cool!

Thanks again for looking into my first suggestion. It'll be extremely helpful.

**Comment by jspegele** [comment]
You can now see this breakdown by clicking the new info icon next to your total mastery score.
![image](https://user-images.githubusercontent.com/8548932/194103816-7e428cd4-11ff-43f9-9f01-ac010c09afc1.png)

I'm not sure about breaking out the tabs further. Having that many tabs would make the UI too cumbersome.
