### ISSUE TITLE
KUVA AYANGA's maximum level is 30

### ISSUE THREAD

**Issue by TakuNico** [jspegele/warframe-mastery-checklist#3]
As the title suggests, unlike other KUVA weapons, only AYANGA has a maximum level of 30.
So there is a 1000 point gap with the actual in-game mastery.
Please make it possible to set the maximum level of KUVA AYANGA up to 40.
![ayanga](https://user-images.githubusercontent.com/74977740/202582683-4be04bfc-3542-4ea4-88e4-a779e0330252.png)

**Comment by jspegele** [comment]
Fixed. Thank you for reporting this.
